# ============================================================================
# StudyVault -- Build Script
# Scans files/ for .html files, extracts metadata, injects navigation,
# and generates files-data.js for the website to consume.
# ============================================================================

# Use script's own directory as the project root
$ProjectRoot = $PSScriptRoot
$FilesDir = Join-Path $ProjectRoot "files"
$OutputFile = Join-Path $ProjectRoot "files-data.js"

# -- Navigation HTML to inject -----------------------------------------------
$NavHtml = @'
<!-- StudyVault Navigation -->
<a href="../index.html" style="position:fixed;top:16px;left:16px;z-index:99999;display:inline-flex;align-items:center;gap:8px;padding:10px 18px;background:linear-gradient(135deg,rgba(99,102,241,0.9),rgba(139,92,246,0.9));color:white;text-decoration:none;border-radius:12px;font-family:'Inter',system-ui,-apple-system,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.3px;backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,0.15);box-shadow:0 4px 15px rgba(99,102,241,0.3),0 1px 3px rgba(0,0,0,0.2);transition:all 0.3s cubic-bezier(0.4,0,0.2,1);opacity:0.9;" onmouseover="this.style.opacity='1';this.style.transform='translateY(-2px)';this.style.boxShadow='0 6px 20px rgba(99,102,241,0.4),0 2px 5px rgba(0,0,0,0.2)'" onmouseout="this.style.opacity='0.9';this.style.transform='translateY(0)';this.style.boxShadow='0 4px 15px rgba(99,102,241,0.3),0 1px 3px rgba(0,0,0,0.2)'" id="back-to-home"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5"/><polyline points="12 19 5 12 12 5"/></svg>StudyVault Home</a>
'@

# -- Helper: Format file size ------------------------------------------------
function Format-FileSize {
    param([long]$Bytes)
    if ($Bytes -ge 1MB) {
        return "{0:N1} MB" -f ($Bytes / 1MB)
    }
    elseif ($Bytes -ge 1KB) {
        return "{0:N1} KB" -f ($Bytes / 1KB)
    }
    else {
        return "$Bytes B"
    }
}

# -- Helper: Escape a string for JSON ----------------------------------------
function ConvertTo-JsonString {
    param([string]$Value)
    $Value = $Value -replace '\\', '\\'
    $Value = $Value -replace '"', '\"'
    $Value = $Value -replace "`r", '\r'
    $Value = $Value -replace "`n", '\n'
    $Value = $Value -replace "`t", '\t'
    return $Value
}

# -- Helper: Detect category from filename/title -----------------------------
function Get-Category {
    param([string]$FileName, [string]$Title)
    $quizKeywords = 'quiz|question|bank|exam|test|mcq'
    if ($FileName -match $quizKeywords -or $Title -match $quizKeywords) {
        return "quiz"
    }
    return "lecture"
}

# ============================================================================
# MAIN
# ============================================================================

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  StudyVault Build Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if files/ directory exists
if (-not (Test-Path $FilesDir)) {
    Write-Host "[!] Directory not found: $FilesDir" -ForegroundColor Red
    Write-Host "    Creating empty files-data.js..." -ForegroundColor Yellow

    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $emptyJs = "/**`n * StudyVault - Auto-generated file manifest`n * Generated by build.ps1`n * Last updated: $timestamp`n * `n * To regenerate: Run .\build.ps1 in the project root`n */`nwindow.STUDYVAULT_FILES = [];"
    Set-Content -Path $OutputFile -Value $emptyJs -Encoding UTF8
    Write-Host "[OK] Empty files-data.js generated (no files directory)." -ForegroundColor Green
    exit 0
}

# Get all supported files in files/
$allowedExtensions = @('.html', '.htm', '.pdf', '.txt', '.doc', '.docx', '.ppt', '.pptx', '.md')
$targetFiles = Get-ChildItem -Path $FilesDir -File | Where-Object { $allowedExtensions -contains $_.Extension.ToLower() }

if ($targetFiles.Count -eq 0) {
    Write-Host "[!] No supported files found in $FilesDir" -ForegroundColor Yellow
    Write-Host "    Creating empty files-data.js..." -ForegroundColor Yellow

    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $emptyJs = "/**`n * StudyVault - Auto-generated file manifest`n * Generated by build.ps1`n * Last updated: $timestamp`n * `n * To regenerate: Run .\build.ps1 in the project root`n */`nwindow.STUDYVAULT_FILES = [];"
    Set-Content -Path $OutputFile -Value $emptyJs -Encoding UTF8
    Write-Host "[OK] Empty files-data.js generated (no files found)." -ForegroundColor Green
    exit 0
}

Write-Host "[*] Found $($targetFiles.Count) file(s) in files/" -ForegroundColor Green
Write-Host ""

# -- Process each file -------------------------------------------------------
$fileEntries = @()
$totalSize = 0
$injectedCount = 0

foreach ($file in $targetFiles) {
    $isHtml = ($file.Extension.ToLower() -eq '.html' -or $file.Extension.ToLower() -eq '.htm')
    
    # --- fileName: exact original file name without extension ---
    $fileNameClean = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $filePath = "files/$($file.Name)"
    $sizeBytes = $file.Length
    $totalSize += $sizeBytes
    $sizeFormatted = Format-FileSize -Bytes $sizeBytes
    
    $title = $fileNameClean -replace '^\d+[\s_\-]*', ''
    $description = ""
    $lineCount = 0
    
    if ($isHtml) {
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        $lineCount = ($content -split "`n").Count
        
        # Inject navigation
        if ($content -notmatch 'id="back-to-home"') {
            if ($content -match '(<body[^>]*>)') {
                $bodyTag = $Matches[0]
                $content = $content -replace [regex]::Escape($bodyTag), "$bodyTag`n$NavHtml"
                Set-Content -Path $file.FullName -Value $content -Encoding UTF8 -NoNewline
                Write-Host "  [+] Injected navigation into $($file.Name)" -ForegroundColor Magenta
                $injectedCount++
            } else { Write-Host "  [!] No <body> tag found in $($file.Name)" -ForegroundColor Yellow }
        } else { Write-Host "  [=] Navigation already present in $($file.Name)" -ForegroundColor DarkGray }
    } else {
        Write-Host "  [=] Added non-HTML file: $($file.Name)" -ForegroundColor DarkGray
    }

    $category = Get-Category -FileName $fileNameClean -Title $title

    # --- Embed content for text/markdown files to avoid CORS on file:/// ---
    $fileContent = ""
    if ($file.Extension.ToLower() -match '\.(txt|md)$') {
        $fileContent = Get-Content -Path $file.FullName -Raw -Encoding UTF8
    }

    # Build entry object
    $entry = @{
        fileName      = $fileNameClean
        filePath      = $filePath
        title         = $title
        description   = $description
        sizeBytes     = $sizeBytes
        sizeFormatted = $sizeFormatted
        lines         = $lineCount
        category      = $category
        textContent   = $fileContent
    }
    $fileEntries += $entry
}

# -- Sort alphabetically by fileName -----------------------------------------
$fileEntries = $fileEntries | Sort-Object { $_.fileName }

# -- Build the JavaScript output ----------------------------------------------
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$emdash = [char]0x2014
$jsLines = @()
$jsLines += "/**"
$jsLines += " * StudyVault $emdash Auto-generated file manifest"
$jsLines += " * Generated by build.ps1"
$jsLines += " * Last updated: $timestamp"
$jsLines += " * "
$jsLines += " * To regenerate: Run .\build.ps1 in the project root"
$jsLines += " */"
$jsLines += "window.STUDYVAULT_FILES = ["

for ($i = 0; $i -lt $fileEntries.Count; $i++) {
    $e = $fileEntries[$i]
    $comma = if ($i -lt $fileEntries.Count - 1) { "," } else { "" }

    $fnEsc   = ConvertTo-JsonString $e.fileName
    $fpEsc   = ConvertTo-JsonString $e.filePath
    $ttEsc   = ConvertTo-JsonString $e.title
    $descEsc = ConvertTo-JsonString $e.description
    $sfEsc   = ConvertTo-JsonString $e.sizeFormatted
    $tcEsc   = ConvertTo-JsonString $e.textContent

    $jsLines += "  {"
    $jsLines += "    `"fileName`": `"$fnEsc`","
    $jsLines += "    `"filePath`": `"$fpEsc`","
    $jsLines += "    `"title`": `"$ttEsc`","
    $jsLines += "    `"description`": `"$descEsc`","
    $jsLines += "    `"sizeBytes`": $($e.sizeBytes),"
    $jsLines += "    `"sizeFormatted`": `"$sfEsc`","
    $jsLines += "    `"lines`": $($e.lines),"
    $jsLines += "    `"category`": `"$($e.category)`","
    $jsLines += "    `"textContent`": `"$tcEsc`""
    $jsLines += "  }$comma"
}

$jsLines += "];"

# -- Write output file -------------------------------------------------------
$jsContent = $jsLines -join "`n"
Set-Content -Path $OutputFile -Value $jsContent -Encoding UTF8

# -- Print summary ------------------------------------------------------------
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Build Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Files found:       $($fileEntries.Count)" -ForegroundColor White
Write-Host "  Nav injected:      $injectedCount file(s)" -ForegroundColor Magenta
Write-Host ""
Write-Host "  -- File Details --" -ForegroundColor DarkCyan

foreach ($e in $fileEntries) {
    $catLabel = if ($e.category -eq "quiz") { "[Quiz]" } else { "[Lecture]" }
    Write-Host "    $($e.fileName)  ($($e.sizeFormatted), $($e.lines) lines)  $catLabel" -ForegroundColor White
}

$totalFormatted = Format-FileSize -Bytes $totalSize
Write-Host ""
Write-Host "  Total size:        $totalFormatted" -ForegroundColor White
Write-Host ""
Write-Host "  [OK] files-data.js generated at:" -ForegroundColor Green
Write-Host "       $OutputFile" -ForegroundColor Green
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Build complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
