/**
 * StudyVault — Auto-generated file manifest
 * Generated by build.ps1
 * Last updated: 2026-06-20 20:17:58
 * 
 * To regenerate: Run .\build.ps1 in the project root
 */
window.STUDYVAULT_FILES = [
  {
    "fileName": "00_طبيعة_الامتحان",
    "filePath": "files/00_طبيعة_الامتحان.md",
    "title": "طبيعة_الامتحان",
    "description": "",
    "sizeBytes": 1574,
    "sizeFormatted": "1.5 KB",
    "lines": 0,
    "category": "lecture",
    "textContent": "# خلاصة طبيعة الامتحان\n\nبناءً على الرسائل الموضحة، إليك تفاصيل وطبيعة الامتحان:\n\n## هيكل الامتحان\n* يتكون الامتحان من أسئلة اختيار من متعدد (MCQ) وأسئلة مقالية.\n\n## تعليمات هامة للحل\n* **أسئلة الاختيار من متعدد (MCQ):** يجب كتابة إجاباتها بالكامل في صفحة واحدة وبشكل منظم لتسهيل عملية التصحيح.\n* **الرسومات التوضيحية:** أي جزء أو سؤال له رسمة توضيحية في المنهج، أنت مطالب برسمها في إجابتك حتى لو لم يُطلب منك ذلك صراحةً في السؤال.\n\n## الأسئلة المقالية\n* **سؤال العرض التقديمي (Presentation):** سيكون هناك سؤال يطلب منك تلخيص الموضوع الذي قمت بشرحه في العرض التقديمي (الشفوي). يجب أن يتضمن التلخيص الرسومات والأكواد البسيطة إذا كانت جزءاً من العرض الخاص بك.\n* **أسئلة الأكواد:** توقع وجود أسئلة تتطلب كتابة أكواد أو (Pseudocode) بسيطة وإجاباتها قصيرة. ستتركز هذه الأسئلة بشكل أساسي في المواضيع التالية:\n  * التزامن (Synchronisation) مثل Peterson's solution وغيرها.\n  * خيوط المعالجة (Threads)\n  * الاتصال (Communication) مثل Process communication.\n\n"
  },
  {
    "fileName": "CPU Scheduling Examples",
    "filePath": "files/CPU Scheduling Examples.pdf",
    "title": "CPU Scheduling Examples",
    "description": "",
    "sizeBytes": 1041367,
    "sizeFormatted": "1,017.0 KB",
    "lines": 0,
    "category": "quiz",
    "textContent": ""
  },
  {
    "fileName": "Lec 1 & Sec 1 - summary - OS",
    "filePath": "files/Lec 1 & Sec 1 - summary - OS.pdf",
    "title": "Lec 1 & Sec 1 - summary - OS",
    "description": "",
    "sizeBytes": 1430650,
    "sizeFormatted": "1.4 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 2+3 & Sec - summary - OS",
    "filePath": "files/Lec 2+3 & Sec - summary - OS.pdf",
    "title": "Lec 2+3 & Sec - summary - OS",
    "description": "",
    "sizeBytes": 1230197,
    "sizeFormatted": "1.2 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 4 & Sec - summary - OS",
    "filePath": "files/Lec 4 & Sec - summary - OS.pdf",
    "title": "Lec 4 & Sec - summary - OS",
    "description": "",
    "sizeBytes": 1541802,
    "sizeFormatted": "1.5 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "حل مسألة CPU Scheduling",
    "filePath": "files/حل مسألة CPU Scheduling.pdf",
    "title": "حل مسألة CPU Scheduling",
    "description": "",
    "sizeBytes": 332051,
    "sizeFormatted": "324.3 KB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS",
    "filePath": "files/حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS.pdf",
    "title": "حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS",
    "description": "",
    "sizeBytes": 2719348,
    "sizeFormatted": "2.6 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  }
];
