/**
 * StudyVault — Auto-generated file manifest
 * Generated by build.ps1
 * Last updated: 2026-06-22 22:14:10
 * 
 * To regenerate: Run .\build.ps1 in the project root
 */
window.STUDYVAULT_FILES = [
  {
    "fileName": "00_طبيعة_الامتحان",
    "filePath": "files/00_طبيعة_الامتحان.md",
    "title": "طبيعة_الامتحان",
    "description": "",
    "sizeBytes": 2359,
    "sizeFormatted": "2.3 KB",
    "lines": 0,
    "category": "lecture",
    "textContent": "### 1. هيكل الامتحان:\n*   **MCQ:** يجب حله في صفحة واحدة وبشكل منظم. للتدريب راجع ملف `OS Exams MCQ.pdf`.\n*   **المقالي:** يشمل مسائل، رسومات، وأكواد/Pseudocode، وسؤال البريزنتيشن.\n\n### 2. الرسومات التوضيحية (Diagrams):\n*   **القاعدة:** إجبارية لأي سؤال نظري يمتلك رسمة في المنهج، حتى وإن لم تُطلب صراحة.\n*   **للمذاكرة:** راجع ملف `OS important diagrams.pdf`.\n*   **أمثلة من الامتحانات:**\n    *   رسمة (7-state process model): تكررت في `Midterm 2025.pdf` و `Final OS.pdf` و `OS FINAL 2020(Dr.Reda).pdf`.\n    *   رسمة (Context Switch): تكررت في `OS _ written problems.pdf`.\n\n### 3. أسئلة الأكواد (Pseudocode & Code):\n*   **طبيعتها:** أكواد بسيطة وإجاباتها قصيرة، تركز على: Synchronization، Threads، و Communication.\n*   **للمذاكرة:** النظري في `Lecture 7.pdf` و `Lecture 8.pdf`. العملي في `section_7.pdf` و `section_8.pdf`.\n*   **أمثلة من الامتحانات:**\n    *   كود BlockingQueue باستخدام (Semaphores): تكرر في `Final 2024(Dr.Reda).pdf` و `Final OS 2023(Dr.Reda).pdf`.\n    *   كود Producer-Consumer: جاء في ``OS _ Final 2025(Dr.Reda).pdf``.\n\n### 4. المسائل المقالية ( المتكررة والمتوقع مجيئها ):\n*   **مسألة CPU Scheduling:** (رسم Gantt Chart وحساب Waiting Time). للمذاكرة والتدريب راجع `Scheduling Problems.pdf` و `OS _ final problems.pdf`.\n*   **مسألة Disk Scheduling:** لحساب المسافات (FCFS, SCAN.. الخ). للتدريب راجع `حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS.pdf` و `Final 2024(Dr.Reda).pdf`.\n\n### 5. سؤال الـ Presentation:\n*   سؤال مقالي يطلب تلخيص موضوع العرض التقديمي الخاص بك في امتحان الشفوي، ويجب أن يتضمن الرسومات أو الأكواد الخاصة به إن وُجدت.\n\n## Access the Files\nYou can access all the referenced files via this Google Drive link: \n[Google Drive Folder](https://drive.google.com/drive/folders/1ohi-oQ2vJJIYINBfe_MxQm2I3CEg_4cE?usp=drive_link)"
  },
  {
    "fileName": "01_OS question bank",
    "filePath": "files/01_OS question bank.html",
    "title": "OS question bank",
    "description": "",
    "sizeBytes": 437843,
    "sizeFormatted": "427.6 KB",
    "lines": 7846,
    "category": "quiz",
    "textContent": ""
  },
  {
    "fileName": "02_OS_Diagrams",
    "filePath": "files/02_OS_Diagrams.html",
    "title": "OS_Diagrams",
    "description": "",
    "sizeBytes": 42172,
    "sizeFormatted": "41.2 KB",
    "lines": 943,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "CPU Scheduling Examples",
    "filePath": "files/CPU Scheduling Examples.pdf",
    "title": "CPU Scheduling Examples",
    "description": "",
    "sizeBytes": 1041367,
    "sizeFormatted": "1,017.0 KB",
    "lines": 0,
    "category": "quiz",
    "textContent": ""
  },
  {
    "fileName": "Lec 1 & Sec 1 - summary",
    "filePath": "files/Lec 1 & Sec 1 - summary.pdf",
    "title": "Lec 1 & Sec 1 - summary",
    "description": "",
    "sizeBytes": 1430650,
    "sizeFormatted": "1.4 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 2+3 & Sec - summary",
    "filePath": "files/Lec 2+3 & Sec - summary.pdf",
    "title": "Lec 2+3 & Sec - summary",
    "description": "",
    "sizeBytes": 1230197,
    "sizeFormatted": "1.2 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 4 & Sec - summary",
    "filePath": "files/Lec 4 & Sec - summary.pdf",
    "title": "Lec 4 & Sec - summary",
    "description": "",
    "sizeBytes": 1541802,
    "sizeFormatted": "1.5 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 5 - summary",
    "filePath": "files/Lec 5 - summary.pdf",
    "title": "Lec 5 - summary",
    "description": "",
    "sizeBytes": 4761040,
    "sizeFormatted": "4.5 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 6 - summary",
    "filePath": "files/Lec 6 - summary.pdf",
    "title": "Lec 6 - summary",
    "description": "",
    "sizeBytes": 5790182,
    "sizeFormatted": "5.5 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 7 - summary",
    "filePath": "files/Lec 7 - summary.pdf",
    "title": "Lec 7 - summary",
    "description": "",
    "sizeBytes": 6892709,
    "sizeFormatted": "6.6 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 8 - summary",
    "filePath": "files/Lec 8 - summary.pdf",
    "title": "Lec 8 - summary",
    "description": "",
    "sizeBytes": 5888954,
    "sizeFormatted": "5.6 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "Lec 9 - summary",
    "filePath": "files/Lec 9 - summary.pdf",
    "title": "Lec 9 - summary",
    "description": "",
    "sizeBytes": 4827836,
    "sizeFormatted": "4.6 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "حل مسألة CPU Scheduling",
    "filePath": "files/حل مسألة CPU Scheduling.pdf",
    "title": "حل مسألة CPU Scheduling",
    "description": "",
    "sizeBytes": 366357,
    "sizeFormatted": "357.8 KB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  },
  {
    "fileName": "حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS",
    "filePath": "files/حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS.pdf",
    "title": "حلول_مسائل_امتحانات_ميدترم_وفاينل_سابقة_OS",
    "description": "",
    "sizeBytes": 2719348,
    "sizeFormatted": "2.6 MB",
    "lines": 0,
    "category": "lecture",
    "textContent": ""
  }
];
